#pragma once

#define FLOW_TAP_TERM 70
#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 200

#define PERMISSIVE_HOLD

#define COMBO_COUNT 3
#define TAPPING_TERM_PER_KEY

#define USB_SUSPEND_WAKEUP_DELAY 0

#define BOOTMAGIC_ROW 4
#define BOOTMAGIC_COLUMN 0

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 2
#define MOUSEKEY_TIME_TO_MAX 0
